### ISSUE TITLE
SimulationCudaFacade tries to double-free CUDA alocations

### ISSUE THREAD

**Issue by ChrisKitching** [chrxh/alien#101]
[cudaDeviceReset()](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1gef69dd5c6d0206c2b8d099abac61f217) destroys all memory allocations on the device (among other things).

`~SimulationCudaFacade()` calls `cudaDeviceReset()` at the end of its destructor, meaning that the subsequent destruction of some of its members (such as `EditKernelsLauncher`) ends up trying to cudaFree these allocations after they were already freed by cudaDeviceReset. Fishy.

The program gets away with this by ignoring the return codes, but that's perhaps a bit dubious. A bit of refactoring of the object lifecycles might be called for (as well as not ignoring cuda return codes).

(I tripped over this while fiddling with something else using SCALE's exception mode, which found this unrelated problem :P ).

**Comment by chrxh** [comment]
Thanks for pointing out this error! I have just corrected it (and added a check).
