### ISSUE TITLE
Browser and User Account not working - Network issues?

### ISSUE THREAD

**Issue by Grownz** [chrxh/alien#102]
While having no general network issues, there is a problem with the in-app browser and user account generation (see log.txt snippet below):
![grafik](https://github.com/user-attachments/assets/3d1939cb-1493-45e9-803f-cef9b280dcd6)

Thank you for your time!

**Comment by chrxh** [comment]
Could you please try again? At some times of the day, the server responds a little slowly and the program could run in a timeout. In the mid future I will move to a new server.

**Comment by Grownz** [comment]
I did, but that didn't resolve the issue.
![grafik](https://github.com/user-attachments/assets/f988954b-d979-424e-8542-be35e3eca26a)


The simulation browser shows up empty:
![grafik](https://github.com/user-attachments/assets/7257c7c4-3c58-4bd8-a17e-70b827a37d5e)


And, though i can successlully ping alien-project.org, my browser can't access the website:
![grafik](https://github.com/user-attachments/assets/c0b958f4-e78c-4b3d-a61e-09507a26d4e1)
![grafik](https://github.com/user-attachments/assets/908c5479-ec96-4a12-9627-d0ecb3ead265)
(all in german, but y'all get the idea ;-) )

**Comment by chrxh** [comment]
I cannot reproduce the error. I can open the website as usual. Can you load the website from some other device?

**Comment by Grownz** [comment]
Ok, this is interesting. I tried my Debian alternative to access the website.
First - no luck. But with VPN (NL):
![grafik](https://github.com/user-attachments/assets/f01d52c4-4796-4a76-8eb1-9ab877ce8e17)

This kinda looks either like a DNS-block my ISP did or an IP-block the service does... but in either cases... why? 😖

**Comment by Grownz** [comment]
I changed the DNS-Server and now it works ... Thank you for your time :)
