### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by azrrik** [chrxh/alien#16]
I installed this program via the provided installer on windows.  The program starts, but running the default simulation or loading another simulation will cause the program to freeze.  Is there anything I can do to troubleshoot this?  I have a GTX 1070.

**Comment by chrxh** [comment]
Can you send me the log.txt (should be in bin-folder)?

**Comment by azrrik** [comment]
[log.txt](https://github.com/chrxh/alien/files/6102842/log.txt)

Attached, thanks!

**Comment by chrxh** [comment]
Thank you! I'm not sure if I can find the reason without using a debugger. The examples you have loaded are using all algorithms from the simulation code. I've the suspicion that some of them are not properly running on your graphics card.
There are demo files that use simpler algorithms.
For instance, `examples/simulations/collision.sim`. Does this demo work?

**Comment by azrrik** [comment]
I can load collisions.sim.  When I hit the play button, one frame renders, but no more.  If I then try to exit the application, the autosave dialogue pops up and the application never actually terminates.

**Comment by chrxh** [comment]
Ok, I attach a special version where only the basic physics algorithm are activated:
http://alien-project.org/alien_installer_debug.zip

Does freezing still occur?

**Comment by azrrik** [comment]
The attached version runs for about 10 seconds then crashes.  I sent the bug report when prompted and attached the log:
[log.txt](https://github.com/chrxh/alien/files/6103429/log.txt)

**Comment by chrxh** [comment]
Many thanks for trying ! One more request: I have rougly 300 automatic tests which test all features of the simulation code.  Here is a compiled version: `alien-project.org/Tests.zip`
Simple unpack and start Tests.exe. The tests are executed in a console. Which ones are failing?

**Comment by azrrik** [comment]
No worries!  Thanks for helping me troubleshoot the issue.  The `CleanupGpuTests.testCleanupCells` test never finishes.  (I waited a couple minutes... not sure if it should take longer?)  Attached is the output from Tests.exe.

[test_out.txt](https://github.com/chrxh/alien/files/6103785/test_out.txt)

**Comment by chrxh** [comment]
This test possibly recreates the timeout problem you have described at the beginning. The test checks the garbage collector.
At this time, I see no way to further address the problem without having your hardware. 

The only thing what remains to try is to reduce the number of CUDA blocks in the simulator (under Settings -> General settings -> Number of blocks), e.g. halve the number, because it could be a problem with the size of the shared memory. Could you please try this on the special version I sent?

**Comment by azrrik** [comment]
It runs when I cut the CUDA blocks to 128.  Thanks for the help!

**Comment by chrxh** [comment]
Super! Also the freezing no longer occurs?
The number of threads per block and block is a science in itself. Currently, no automatism is implemented. Too low values lead to poor performance and too high values can lead to crashes.

**Comment by azrrik** [comment]
Nope, no freezing when the number of CUDA blocks is 128.
