### ISSUE TITLE
CUDA error 222 on Geforce GTX 1650 Ti 

### ISSUE THREAD

**Issue by liquid-void** [chrxh/alien#22]
Hi,

when trying to launch alien I keep getting the following critical error:

`CUDA error at CudaSimulation.cu:382 code=222(<unknown>) "cudaMemcpyToSymbol( cudaSimulationParameters, &parameters, sizeof(SimulationParameters), 0, cudaMemcpyHostToDevice)"`

I'm on Windows 10 21H1, NVIDIA Geforce GTX 1650 Ti with latest CUDA version 11.3.1 installed.
Any idea how to fix this?

Thanks

**Comment by chrxh** [comment]
Hi,
unless you want to compile the project yourself, it's not necessary to install the CUDA toolkit because the CUDA runtime library is statically linked in the binaries.
Hopefully a solution could be for you to update your Nvidia graphics driver. Each CUDA version requires a minimum driver version.

**Comment by chrxh** [comment]
PS: This seems to be the same issue as described here https://forums.developer.nvidia.com/t/provided-ptx-was-compiled-with-an-unsupported-toolchain-error-using-cub/168292

**Comment by chrxh** [comment]
Does a driver update solve your problem?

**Comment by liquid-void** [comment]
Sorry for the late response, I believe you are right that it's a driver version issue,
but unfortunately I'm unable to confirm yet. I've tried updating my driver multiple times.
However, the latest officially supported NVIDIA driver from the manufacturer of my MSI notebook, is 451.83. 
Any newer release directly from NVIDIA just fails with "installer failed".

Thanks for the hint, though, but I guess I will need to wait for a newer officially supported driver from MSI.
I don't believe it's an issue from your side. You can close the issue.
