### ISSUE TITLE
GUI freezes when I hit run

### ISSUE THREAD

**Issue by alcino** [chrxh/alien#23]
Seems similar to #16 . When I start the program I can move around, zoom in/out, load different sims, etc. When I hit run the interface freezes and the simulation doesn't run either. The menus still work but if I try to quit it gets stuck in an autosaving prompt. I checked the log and nothing seems funky, it registers sim start/stop commands fine and also registers camera movements, even though they don't happen.

I have a GeForce GTX 1060 3GB, which I know is less than the recommended memory, but I don't see why it would fail entirely since the task manager shows only ~2GB of video memory being used. I already tried reducing the number of blocks and threads, to no avail.

**Comment by chrxh** [comment]
This issue could be related to https://github.com/chrxh/alien/issues/21 ?
I'll provide a compiled version of the automatic tests soon.

**Comment by chrxh** [comment]
Copied from #21:
The installer of the latest version 2.5.3 now provides ~ 300 compiled integration tests.
Could you please run them (Tests.exe in the bin folder)? Alternatively, you can compile them for yourself (it's the Tests project).
Possibly 1-2 tests failed indeterministically (I haven't analyzed them yet... this can be ignored for the moment,).
Thanks a lot!

**Comment by graphnode** [comment]
I'm having the same or similar issue, the view freezes after I hit run (can still use the menubar and the scrollbars show that I'm zooming) and the gpu is 100%.

I'm using a GTX 1080 8GB with driver 466.77.

Running the Tests.exe stops here:
![image](https://user-images.githubusercontent.com/216518/122053992-2c537480-cddf-11eb-9537-f1ad41b5ebe6.png)
