### ISSUE TITLE
Ubuntu support? 

### ISSUE THREAD

**Issue by lorepieri8** [chrxh/alien#26]
Any plans to support this on ubuntu? 
Or perhaps a docker container?

**Comment by chrxh** [comment]
Some github users are helping me to migrate it to Linux. So there will hopefully a support in near future.

**Comment by justinkterry** [comment]
Could you please link to where the development for that is happening?

**Comment by chrxh** [comment]
Alien can now be build in Linux. The changes including cmake script files have been merged to the developer branch (see https://github.com/chrxh/alien/pull/24).
