### ISSUE TITLE
Cannot find impactor example

### ISSUE THREAD

**Issue by drozzy** [chrxh/alien#30]
Hi,
I recently installed alien on windows using the provided installer, and started following the tutorial here:
https://alien-project.org/documentation/Creatingaformationofmachines.html

During the part where it says to open the `/examples/collections/impactor.col` collection, I can't find it in the example diretories.
I see `interceptor.col` and other files, but no `impactor.col`.

**Comment by drozzy** [comment]
In fact I see it's not part of the code repo either:
https://github.com/chrxh/alien/tree/develop/examples/collections

**Comment by drozzy** [comment]
Oh, it's called `interceptor`.

**Comment by chrxh** [comment]
Hi,
Thanks for the hint!
The documentation is not quite up to date anymore. Since version 2.5 the appearance and some naming have changed a bit.
I'm currently updating the docu step by step.
