### ISSUE TITLE
Unknown type particleMap and CellMap in struct SimylationData 

### ISSUE THREAD

**Issue by geotyper** [chrxh/alien#31]
Try to compile projects with another graphic backend on Ubuntu
Compiler can't found  particleMap and CellMap
![Screenshot at 2021-06-26 16-26-00](https://user-images.githubusercontent.com/30755433/123514422-a87d7000-d69b-11eb-83c0-cf27424fb51e.png)

As idea they located in some file from #include section

**Comment by geotyper** [comment]
Find

**Comment by chrxh** [comment]
Cool :) What graphic backend are you using?

**Comment by geotyper** [comment]
BGFX as backend.
don't want to recompile all project, as idea to experiments with your collision system, arrays, maps on cuda.

project looks interesting, idea of self growing clusters from cell looks like list of small spaces of cellular automata floating in big space, try to find any evolution code (like genetic mutations or other methods) but couldn't in short view.
Now have some unstable behavior on cuda kernels in part of read data from gpu, but kernels have some changes from your source code, so can be my errors.

**Comment by chrxh** [comment]
Thanks!
An evolution simulation is currently only possible by creating a world with replicators and food and using a mutation rate (can be configured in SimulationParameters).
More details are in the docu: https://alien-project.org/documentation/Evolutionexperiments.html
