### ISSUE TITLE
The map is 4 times smaller than it should be and cannot be enlarged.

### ISSUE THREAD

**Issue by TeiBri** [chrxh/alien#32]
Version: v2.5.3

I'm sending a video where it's most clear what I mean.

https://user-images.githubusercontent.com/62265168/123537866-08bef100-d732-11eb-9045-a055f2d09291.mp4

**Comment by chrxh** [comment]
It looks like the OpenGL viewport is set when the app is not yet maximized/fullscreen.
Could you please try this fix?
https://alien-project.org/files/alien_bugfix.zip
Does it solve this issue?

**Comment by TeiBri** [comment]
> It looks like the OpenGL viewport is set before the app is maximized/fullscreen.
> Could you please try this fix?
> https://alien-project.org/files/alien_bugfix.zip
> Does it solve this issue?

Unfortunately, it didn't work out. Still the same. :(

**Comment by chrxh** [comment]
If you zoom more than 32x, then the editor mode should pop up automatically.
Do you then see the world in the correct size?
If so, then when you zoom out, does it stay at the correct size?

**Comment by TeiBri** [comment]
> If you zoom more than 32x, then the editor mode should pop up automatically.
> Do you then see the world in the correct size?
> If so, then when you zoom out, does it stay at the correct size?

Yes. When I get into that 2 mode, where it's very close and I see the numbers of each cell, it's in normal size.

**Comment by chrxh** [comment]
Ok, and when you then zoom out?

**Comment by TeiBri** [comment]
> Ok, and when you then zoom out?

That's what happens in the video. It's 4 times smaller.

**Comment by chrxh** [comment]
I've prepared a special version again under https://alien-project.org/files/alien_bugfix.zip with 2 changes:
- it opens a console beside the app
- I simply doubled the width and height of the viewport (just for testing)

Could you please start and end the program and send me the content of the console? (the console should be visible after closing)

Is the map shown normally?

Thanks!

**Comment by TeiBri** [comment]
> I've prepared a special version again under https://alien-project.org/files/alien_bugfix.zip with 2 changes:
> 
> * it opens a console beside the app
> * I simply doubled the width and height of the viewport (just for testing)
> 
> Could you please start and end the program and send me the content of the console? (the console should be visible after closing)
> 
> Is the map shown normally?
> 
> Thanks!

It's 50 to 50, because... watch the video.

https://user-images.githubusercontent.com/62265168/123546185-db873880-d75b-11eb-97ac-97411b5dfe8e.mp4

**Comment by chrxh** [comment]
The actual problem is not the viewport. It could be a clipping problem. 
Can you please try again: https://alien-project.org/files/alien_bugfix.zip ?
A screenshot of the open program suffices.

The view should still not be correct in this version but if it look different from your initial video I might found the problem and could fix it.

**Comment by TeiBri** [comment]
We are back to the beginning ... D:
https://user-images.githubusercontent.com/62265168/123549489-936f1280-d769-11eb-937a-de4c0bd45c49.mp4

**Comment by chrxh** [comment]
hmm.
Could it be that you are using a higher resolution than 1920x1080 (e.g. 4k) and scaling the apps in Windows by a factor of, say, 2?

**Comment by chrxh** [comment]
I mean, have you set more than 100% in this setting?
![screenshot](https://user-images.githubusercontent.com/73127001/123550726-3d04d280-d76f-11eb-9a96-147d9917712f.PNG)

**Comment by TeiBri** [comment]
> I mean, have you set more than 100% in this setting?
> ![screenshot](https://user-images.githubusercontent.com/73127001/123550726-3d04d280-d76f-11eb-9a96-147d9917712f.PNG)

Yes. I have 200%

**Comment by chrxh** [comment]
That is the problem :) The scaling from Windows does not apply to the map view. You should switch to 100% and it should work.

**Comment by TeiBri** [comment]
> That is the problem :) The scaling from Windows does not apply to the map view. You should switch to 100% and it should work.

Oh God. It works and so stupid mistake. I apologize for your loss of time :D. Right now I have set 1920x1080 and 100% and it works normal without bugfix v2.5.3. I apologize again.

**Comment by chrxh** [comment]
No apology! This was new for me too. I will make a FAQ and mention it :)
