### ISSUE TITLE
Can't read from files

### ISSUE THREAD

**Issue by coderguy57** [chrxh/alien#47]
When ever I try to open an simulation I get 'The selected file could not be opened.'
It is cause the Serializer::deserializeDataDescription throws "no data found".
Any idea why it does this?

**Comment by chrxh** [comment]
What system are you using (Win/Linux/Mac)?
Which file exactly did you try to open?

**Comment by chrxh** [comment]
Is the default simulation loaded at the first start or do you just see a blank background?

If not I can think of 2 error causes:
- To load a simulation, the .sim file is needed together with .settings.json and .symbols.json. If the *.json files are missing, you get this error message among others. Can you still check this?
- It could also indicate a problem with cross-platform serialization support. The examples were created in Windows. However, the libraries used for compression (stb_[en]compress) and for serialization (cereal) should do that. Hm....

**Comment by coderguy57** [comment]
Yep that worked. Thx !!
We know that's the problem, I can look into why it compression libs don't work

**Comment by chrxh** [comment]
Thanks, that would be great! Maybe some byte ordering problem.... ?!

If the problem can't be solved so easily, I could also take out the compression for now and resave all examples. The files are then unfortunately about twice as large :-/

Note: With the correction above, however, only the deserialization is done without compression. On saving, it is still activated.

**Comment by chrxh** [comment]
I'm currently trying to use zstr/zlib for compression.  It would be great if you could try if it works?
The source code is in the branch `features/zlib`. Here is the simulation file for testing:
[zlib_test.zip](https://github.com/chrxh/alien/files/8303973/zlib_test.zip)
.

**Comment by coderguy57** [comment]
Yep, that worked perfectly!
You don't happen to have a discord or slack for the project?

**Comment by chrxh** [comment]
Thanks for testing!
I've now converted all examples and changed the Serializer.cpp completely to the new format. It's now on the develop branch.
There is a subreddit for this project at [https://www.reddit.com/r/AlienProject](https://www.reddit.com/r/AlienProject). 
I'd not created a discord or related yet. The development of this project kept me very busy the last few months (and as a result the new version 3.0 will be ready very soon :) .Then I hope to have more time for such things.

**Comment by chrxh** [comment]
I close this issue. If there are further problems with the file format please let me know.
