### ISSUE TITLE
vcpkg install --failed while trying to generate project files

### ISSUE THREAD

**Issue by loukitkhemka** [chrxh/alien#50]
I keep getting "vcpkg install --failed" while I am trying to generate project files both in Windows 10 and Ubuntu.

Any help please? Thank you.

EDIT: I hate C++ projects for this specific reason. They simply don't work 99% of the time. Sure, I maybe novice, but there are simply too many package managers, compilers and build tool chain BS. What to learn, what to ignore? I simply want to build a project and just understand the source code. It is that simple. But that is a tall order in C++ ecosystem. Just by building the project, you lose all the motivation to even bother looking at the code, because you get tired.

**Comment by chrxh** [comment]
Compiling C++ projects can unfortunately be quite painful. On my developer machine I did the following:
- install MS Visual Studio with CMake and Win SDK (I use VS 2019 but I guess that 2022 should also work)
- set the directory for CMake in the path system variable
- install CUDA Toolkit
And then check out the repository with git and run the build commands from the readme.
Does this work?

**Comment by chrxh** [comment]
I tried compiling it on a fresh system with Windows 11. I noticed that certain download mirrors in the used vcpkg version do not work.
Try the following:  In the directory ./external/vcpkg enter the command (which switches to a more recent vcpkg version)
`git switch d8783052cbf85bb5b1777b58b998c88d99357943 --detach`
and then follow the instructions from the ALIEN readme. I should update the newer vcpkg commit in the repro.

**Comment by loukitkhemka** [comment]
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
Run vcvarsall.bat to get Visual Studio env failed with exit code 1

I am getting the above error.

**Comment by chrxh** [comment]
Did you do the same steps as I described? Which Visual Studio version are you using?

About your error message, I find the following solution in the search:
https://stackoverflow.com/questions/72125949/vcpkg-install-package-error-run-vcvarsall-bat-to-get-visual-studio-env-failed-w
Have you already tried this?

**Comment by loukitkhemka** [comment]
Yes that has worked. Thank you.
