### ISSUE TITLE
Problems on building the sources on Windows

### ISSUE THREAD

**Issue by Gardene-el** [chrxh/alien#56]
i built the source by following the direction on readme but finally failed. and idk how to descripe my problem, so i share a screenshot which contains whole process i have done on cmd.
![BIKP(QW0`1Q% 2PJ$LOMLNP](https://user-images.githubusercontent.com/103943173/191234188-a9b2eb2b-1708-4411-86c3-adb20f399ed7.png)

**Comment by Gardene-el** [comment]
i tried to find the cause of problem on building process, and summarized two potential attribution: i don't install Nsight Visual Studio Edition on installing CUDA because it is always failed, and i don't do anything to configurate the ide because i don't know how to do so.

**Comment by chrxh** [comment]
It should be sufficient to install Visual Studio 2022 and CUDA Toolkit. In your case it already fails already at the installation of the package manager vcpkg.
There is a log file mentioned in the message. What is written there?

**Comment by Gardene-el** [comment]
> It should be sufficient to install Visual Studio 2022 and CUDA Toolkit. In your case it already fails at the installation of the package manager vcpkg. There is a log file mentioned in the message. What is written there?

do you mean error MSB1009? it is "project file don't exist". and then "switch: All_BUILD.vcxproj"

**Comment by chrxh** [comment]
> do you mean error MSB1009? it is "project file don't exist". and then "switch: All_BUILD.vcxproj"

In your first message there is written: "See logs for more information: C:\User\[...]\vcpkg-bootstrap.log"
Maybe in this log-file are more details about your problem.

How did you install CMake?
You can install it using the Visual Studio 2022 installer.
![image](https://user-images.githubusercontent.com/73127001/191850014-7f2d6aef-ec47-4275-9b9b-41aa25875a4d.png)

Does that solves the problem?

**Comment by Gardene-el** [comment]
oh, sorry, now i finally understand your meaning. i have installed CMake tools for Windows, and this doesn't work. the log file in build folder is said:"'powershell.exe' is not an internal or external command, nor is it a runnable program or batch file"

**Comment by chrxh** [comment]
It seems that you need to install powershell: https://learn.microsoft.com/de-de/powershell
(It was already installed on my system.)

**Comment by Gardene-el** [comment]
thanks a lot, now i've installed powershell and add it to path system variable, so this 'powershell.exe' is not an internal or external command, nor is it a runnable program or batch file" solved, but i still met a new problem on building it.
here is the part screenshot and the file
![NO ~$6IA4T8__ _WV4QHPRU](https://user-images.githubusercontent.com/103943173/192112413-b8bb3482-b24d-4e7e-a6b0-33ab21f2ce91.png)

[vcpkg-manifest-install.log](https://github.com/chrxh/alien/files/9639300/vcpkg-manifest-install.log)

**Comment by caichenyi92** [comment]
您好，您的邮件已收到，我会尽快回复，谢谢。

    


    


    蔡陈翼


    东南大学建筑学院
南京市玄武区四牌楼2号Tel：18652966253

**Comment by chrxh** [comment]
> thanks a lot, now i've installed powershell and add it to path system variable, so this 'powershell.exe' is not an internal or external command, nor is it a runnable program or batch file" solved, but i still met a new problem on building it. this problem happened on `cmake .. -DCMAKE_BUILD_TYPE=Release` i'm sure i'm using the latest portfiles with `git pull` and `.\vcpkg update` neither `git pull --recurse-submodules` nor `git switch d8783052cbf85bb5b1777b58b998c88d99357943 --detach` works here are the error screenshot and the log file 

The problem this time seems to be related to https://github.com/microsoft/vcpkg/issues/25322. The suggested solution there is "So I uninstalled PowerShell I downloaded from the Windows Store and re-downloaded it from another source."
