### ISSUE TITLE
Failed to load texture

### ISSUE THREAD

**Issue by noahmacaulay** [chrxh/alien#64]
I'm trying to build the project on Windows. After following the instructions in the readme, I appear to succeed and get an executable in the 'build/Release' folder, but when I try to run it it immediately closes and writes the following in the log file:

2023-02-20 16-04-50: set full screen mode
2023-02-20 16-04-50: The following exception occurred: Failed to load texture

I am running Windows 10 64-bit. I have Visual Studio 2022 version 17.1.2 installed and CUDA version 11.6.

**Comment by caichenyi92** [comment]
您好，您的邮件已收到，我会尽快回复，谢谢。

    


    


    蔡陈翼


    东南大学建筑学院
南京市玄武区四牌楼2号Tel：18652966253

**Comment by chrxh** [comment]
Hi,
the executable should be built in [...]build\Release\alien.exe. When you run alien.exe directly from the Release folder, it does not find the resource files. Therefore you should run it from the build/working directory in the console via .\Release\alien.exe

**Comment by noahmacaulay** [comment]
Thank you, that worked.
