### ISSUE TITLE
Zooming causes the cells selected to be displaced

### ISSUE THREAD

**Issue by sophxine** [chrxh/alien#89]
When you zoom in or out while selecting cells and moving them the cells are displaced unexpectedly when not moving them. Zooming causes the cells to be moved. This also makes the cursor be at a different position than the selected cells.

**Comment by chrxh** [comment]
It's not clear to me how to reproduce the bug: How can you zoom, select and moving cells at the same time?

**Comment by sophxine** [comment]
To reproduce the bug do:
1. Select a group of cells
2. Move the cells
3. Use the mouse wheel while holding the left mouse button
The more you move the cells before zooming in or out the more it becomes displaced.

**Comment by chrxh** [comment]
Hm, in my case it worked as expected, see
https://github.com/chrxh/alien/assets/73127001/61997450-04e5-4d14-a6df-432c5364a037

**Comment by sophxine** [comment]
Oh it doesn't happen when you have it paused.

**Comment by chrxh** [comment]
I was able to reproduce the bug.
It's fixed in https://github.com/chrxh/alien/commit/cb1a98f0b3dab39b60c7b03ceb968f35fb56f5ab (see https://github.com/chrxh/alien/assets/73127001/a2bbed96-b859-4970-b246-3939656c8743)
The fix will be contained in the next update.
